import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/Provider";
import Header from "@/components/shared/Header/Header";

import FooterController from "@/components/layout/FooterController";
import AutoRefreshProvider from "@/hooks/AutoRefreshProvider";
import AppToaster from "@/components/ui/AppToaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          <AppToaster />
          <Header />
          <AutoRefreshProvider>{children}</AutoRefreshProvider>
          <FooterController />
        </ReduxProvider>
      </body>
    </html>
  );
}
